apiVersion: v1
kind: ServiceAccount
metadata:
  name: myscheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myscheduler-as-kube-scheduler
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myscheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myscheduler-config-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: custom-scheduler
  # deployment namespace
  namespace: kube-system
  labels:
    component: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      serviceAccountName: myscheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: custom-scheduler-ctrl
          image: piaoliangkb/myscheduler:v1.18
          # use local image
          imagePullPolicy: Always
          args:
            - myscheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
            - --scheduler-name=custom-scheduler
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: default-scheduler
    - schedulerName: reqandlog
      plugins:
        preFilter:
          enabled:
          - name: simplelog
          - name: httpreq
        filter:
          enabled:
          - name: simplelog
          - name: httpreq
      pluginConfig:
      - name: "simplelog"
      - name: "httpreq"

