apiVersion: v1
kind: ServiceAccount
metadata:
  name: myscheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myscheduler-as-kube-scheduler
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myscheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myscheduler-config-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: myscheduler-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myscheduler
  namespace: kube-system
  labels:
    component: myscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: myscheduler
  template:
    metadata:
      labels:
        component: myscheduler
    spec:
      serviceAccountName: myscheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: myscheduler-ctrl
          image: piaoliangkb/myscheduler:v1.19
          # use local image
          imagePullPolicy: Always
          args:
            - myscheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
            - --scheduler-name=myscheduler
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    #clientConnection:
      #kubeconfig: "/etc/kubernetes/admin.conf"
    profiles:
    - schedulerName: myscheduler
      plugins:
        preFilter:
          enabled:
          - name: myscheduler
        filter:
          enabled:
          - name: myscheduler 
