apiVersion: v1
kind: Pod
metadata:
    name: nginx-using-default-scheduler
    labels:
        app: nginx
spec:
    schedulerName: default-scheduler
    containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
