apiVersion: v1
kind: Pod
metadata:
    name: notnginx
    labels:
        app: nginx
spec:
    schedulerName: reqandlog
    containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
